#!/bin/sh

######### Script to for firewall tables

#some variables

hof="/sbin/iptables/"
my_ports="22,80,443"#SSH,HTTP and HTTPS
lan="192.168.1.0/24"
any="0.0.0.0/0"




echo "Flushing Firewall and Deleting Chains"

$hof -F
$hof-Z
$hof -X


$hof -P INPUT ACCEPT
$hof -P OUTPUT ACCEPT
$hof -P FORWARD ACCEPT
